### ISSUE TITLE
Error when adding to project: missing npm module

### ISSUE THREAD

**Issue by zischwartz** [akofman/cordova-plugin-boilerplate#2]
When I run 

```
 cordova plugin add ../cordova-plugin-boilerplate/
```

I get an error because I don't have the npm module `xcode` installed.

```
Installing "your.name.space.yourPluginName" for ios
Failed to install 'your.name.space.yourPluginName':Error: Cannot find module 'xcode'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/zach/code/cordova-hello/plugins/your.name.space.yourPluginName/hooks/add_swift_support.js:19:13)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
Error: Cannot find module 'xcode'
```

**Comment by akofman** [comment]
Hey @zischwartz ,

Thanks for your interest. This is not really the purpose of this project to be installed as a plugin. In order to use it, I advice you to clone it and then keep the parts you're interested in for your plugin. 
Also you can add the xcode dependency as a bundled dependency in your plugin.

Concerning the Swift support, I'm working on an other project so that you could add a plugin dependency and the swift support will be activated. I'll keep you informed if you want ;)

**Comment by akofman** [comment]
Ok if you're interrested you can have a look at this repo : https://github.com/akofman/cordova-plugin-add-swift-support
